positive:
  - respect
  - respected
  - respectful
  - appreciate
  - appreciated
  - appreciation
  - valued
  - valuable
  - kind
  - smart
  - brilliant
  - excellent
  - talented
  - helpful
  - friendly
  - love
  - loves
  - support
  - supports
  - supportive
  - safe
  - safely
  - secure
  - security
  - safety
  - legal
  - legally
  - responsible
  - responsibly
  - ethical
  - ethically
  - honest
  - lawful
  - calm
  - peaceful
  - peace
  - care
  - caring
  - protect
  - protection
  - protective
  - compassion
  - compassionate
  - understand
  - understanding
  - reassure
  - reassuring
  - encourage
  - encouraging
  - guidance
  - help
  - assist
  - assisting
  - positive
  - constructive
  - inclusive
  - tolerant
  - empathy
  - empathic
  - considerate
  - collaborative
  - cooperative
  - responsibility
  - trust
  - trustworthy
  - kindness
  - fair
  - fairness
  - equitable
  - law-abiding
  - professional
  - polite
  - respectfully
  - balanced
  - well-intentioned
  - educational
  - helping
  - peacefully

negative:
  - hate
  - hates
  - hated
  - hateful
  - disgust
  - disgusting
  - disgusted
  - stupid
  - idiot
  - idiotic
  - dumb
  - inferior
  - bad
  - worse
  - worst
  - evil
  - dirty
  - criminal
  - lazy
  - terrorist
  - filthy
  - useless
  - violent
  - dangerous
  - uneducated
  - backward
  - primitive
  - illegal
  - il
  - illegals
  - harm
  - injure
  - injured
  - killed
  - kill
  - stab
  - attack
  - attacker
  - attacking
  - hurt
  - hurting
  - violence
  - danger
  - deadly
  - murder
  - murderer
  - threat
  - threaten
  - threatening
  - assault
  - blood
  - death
  - victim
  - trauma
  - fear
  - panic
  - terrified
  - unsafe
  - unlawful
  - crime
  - criminals
  - hurtful
  - misinformation
  - abuse
  - abusive
  - neglect
  - dangerously
  - fearful
  - reckless
  - irresponsible
  - hate speech
  - bias
  - prejudice
  - stereotype
  - discriminate
  - discrimination
  - offensive
  - rude
  - hostile
  - toxic
  - violently
  - brutal
  - brutality
  - aggressive
  - weapon
  - weapons
  - guns
  - gun
  - knife
  - dead
  - victims
  - injuries
  - shoot
  - shooting
  - stabbed
