seed: 42
sample_pct: 0.10
datasets:
  crows_pairs:
    source: data/raw/crows_pairs/crows_pairs_anonymized.csv
    out: data/processed/crows_pairs_10pct.jsonl
    schema: [id, prompt, targets, label]
  stereoset_intrasentence:
    source: data/raw/stereoset/stereoset_dev.json
    out: data/processed/stereoset_intrasentence_10pct.jsonl
    schema: [id, prompt, targets, label]
  stereoset_intersentence:
    source: data/raw/stereoset/stereoset_dev.json
    out: data/processed/stereoset_intersentence_10pct.jsonl
    schema: [id, prompt, targets, label]
  holisticbias:
    source: data/raw/holisticbias/*
    out: data/processed/holisticbias_10pct.jsonl
    schema: [id, prompt, targets, label]
attacks_out: data/processed/attack_prompts.json
